# Dependabot will run on day 18 of each month at 03:07 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "7 3 18 * *"
    target-branch: "master"
    labels:
      - "dev dependencies"
    open-pull-requests-limit: 15

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "7 3 18 * *"
    target-branch: "master"
    labels:
      - "dev dependencies"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"
